version: "3"
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: img-lumen
    container_name: cont-lumen
    restart: unless-stopped
    tty: true
    working_dir: /var/www/
    env_file:
      - .env
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    networks:
      - app-network
networks:
  app-network:
      driver: bridge