name: Docker

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

    deploy:

        name: Setup Gcloud Account
        runs-on: ubuntu-latest
        env:
          IMAGE_NAME: us.gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_APP_NAME }}
        steps:
        - name: Checkout
          uses: actions/checkout@v3

#        - name: Login
#          uses: google-github-actions/setup-gcloud@v0
#          with:
#            project_id: ${{ secrets.GCP_PROJECT_ID }}
#            service_account_email: ${{ secrets.GCP_EMAIL }}
#            service_account_key: ${{ secrets.GCP_CREDENTIALS }}

#        - name: Setting project
#          run: |
#            gcloud config set project ${{ secrets.GCP_PROJECT_ID }}
#            gcloud config set run/region us-central1

        - name: Setup gcloud CLI
        - uses: google-github-actions/setup-gcloud@94337306dda8180d967a56932ceb4ddcf01edae7
          with:
            service_account_key: ${{ secrets.GCP_CREDENTIALS }}
            project_id: ${{ secrets.GCP_PROJECT_ID }}

        - name: helper for authentication
        - run: |-
            gcloud --quiet auth configure-docker

#        - name: Configure Docker
#          run: gcloud auth configure-docker --quiet

#        - name: Configure Docker
#          run: gcloud auth configure-docker --quiet

#        - name: Build Docker image
#          run: docker build -t $IMAGE_NAME .

#        - name: Push Docker image
#          run: docker push $IMAGE_NAME
